export const USER = {
  AJAX_BEGIN: 'USER_AJAX_BEGIN',
  AJAX_END: 'USER_AJAX_END',
  LOGIN: 'USER_LOGIN',
  LOGOUT: 'USER_LOGOUT',
  FETCH_SUCCESS: 'USER_FETCH_SUCCESS'
}

export const PROFILE = {
  AJAX_BEGIN: 'PROFILE_AJAX_BEGIN',
  AJAX_END: 'PROFILE_AJAX_END',
  LOGOUT: 'PROFILE_LOGOUT',
  FETCH_SUCCESS: 'PROFILE_FETCH_SUCCESS'
}

export const AUTHORS = {
  AJAX_BEGIN: 'AUTHORS_AJAX_BEGIN',
  AJAX_END: 'AUTHORS_AJAX_END',
  CLEAR_ALL: 'AUTHORS_CLEAR_ALL',
  FETCH_SUCCESS: 'AUTHORS_FETCH_SUCCESS',
  CREATE_SUCCESS: 'AUTHORS_CREATE_SUCCESS',
  UPDATE_SUCCESS: 'AUTHORS_UPDATE_SUCCESS',
  DELETE_SUCCESS: 'AUTHORS_DELETE_SUCCESS'
}

export const BOOKS = {
  AJAX_BEGIN: 'BOOKS_AJAX_BEGIN',
  AJAX_END: 'BOOKS_AJAX_END',
  CLEAR_ALL: 'BOOKS_CLEAR_ALL',
  FETCH_SUCCESS: 'BOOKS_FETCH_SUCCESS',
  CREATE_SUCCESS: 'BOOKS_CREATE_SUCCESS',
  UPDATE_SUCCESS: 'BOOKS_UPDATE_SUCCESS',
  DELETE_SUCCESS: 'BOOKS_DELETE_SUCCESS'
}
